### ISSUE TITLE
Buscador en /project/things

### ISSUE THREAD

**Issue by pablovg2** [socialinn/socialtocrowd#121]
http://socialtocrowd.org/project/things/?search=material

Ese buscador creo que no busca.. jejej

Fijate en esta página para maquetar la página de resultados: http://lab.enreda.coop/socialtocrowd/index-components.php

**Comment by alesegdia** [comment]
A mí me busca bien, he probado por nombre, descripción, nombre de ONG, descripción de ONG, etc. ¿Puedes decirme la búsqueda que has hecho que no te funciona?
